### ISSUE TITLE
Problem with rst.linker, resulting in a broken link

### ISSUE THREAD

**Issue by sbraz** [jaraco/jaraco.packaging#1]
Hello
The anchor [here](https://github.com/jaraco/jaraco.packaging/blob/5.1/CHANGES.rst#41) is interpreted as a link to an issue which makes the doc look like this:
![image](https://user-images.githubusercontent.com/4833332/41064857-0e0d86dc-69dd-11e8-99db-5e2901cdbdf5.png)

I don't understand how this happens since the pattern seems to require `Issue` to be present before the hash mark:
https://github.com/jaraco/jaraco.packaging/blob/5.1/docs/conf.py#L19

**Comment by jaraco** [comment]
The question mark in `(Issue )?` means that the string 'Issue ' is optional.
