### ISSUE TITLE
Emergent typing failure

### ISSUE THREAD

**Issue by jaraco** [jaraco/jaraco.packaging#14]
Recently, the mypy type checks started failing with the error:

```
37: error: Cannot override class variable (previously declared on base class "Directive") with instance variable  [misc]
```

The relevant code is:

https://github.com/jaraco/jaraco.packaging/blob/35ad39f59971c713bfe13412b4bc56092f966e7e/jaraco/packaging/sphinx.py#L30-L42

And I traced the definition of that class property to:

https://github.com/docutils/docutils/blob/b768e2626088711dec257b0847b563d02700a712/docutils/docutils/parsers/rst/__init__.py#L316-L317

Essentially:

```python
class Directive:
    has_content = False
    """May the directive have content?"""
```

I don't yet understand how `SidebarLinksDirective` is an instance variable.

**Comment by jaraco** [comment]
Here's what [Gemini had to say about it](https://g.co/gemini/share/96db26b4f4e0). Basically, mypy is being unnecessarily nitpicky that I'm using the interface provided by docutils.

**Comment by jaraco** [comment]
The code passed [as recently as 3 months ago](https://github.com/jaraco/jaraco.packaging/actions/runs/7330634246).

**Comment by jaraco** [comment]
Downgrading mypy to 1.7.1 from November, the issue still occurs, so likely the difference is with the typespec for docutils.

**Comment by jaraco** [comment]
Docutils 0.20.1 from last May is still stable.

**Comment by jaraco** [comment]
`types-docutils` appears to have [frequent releases](https://pypi.org/project/types-docutils/#history). What a mess.

**Comment by jaraco** [comment]
Starting with https://pypi.org/project/types-docutils/0.20.0.20240310/, the tests start failing.

**Comment by danieleades** [comment]
> `types-docutils` appears to have [frequent releases](https://pypi.org/project/types-docutils/#history). What a mess.

All typeshed libraries are released daily (whenever they have changes).

If this is an issue you can pin the version

**Comment by jaraco** [comment]
> > `types-docutils` appears to have [frequent releases](https://pypi.org/project/types-docutils/#history). What a mess.
> 
> All typeshed libraries are released daily (whenever they have changes).
> 
> If this is an issue you can pin the version

Thanks for clarifying, and apologies for being abrasive. I thought what I was looking at was a bunch of insignificant changes, assuming that it wasn't possible for a mostly stable module like docutils to evolve so rapidly, but I now see there are rapid and meaningful changes. I'm grateful for that work.
